### ISSUE TITLE
Husky runs during consumers install

### ISSUE THREAD

**Issue by knownasilya** [alexlafroscia/ember-context#178]
```
error /Users/iradchenko/sandbox/ember-context-test/node_modules/@alexlafroscia/ember-context: Command failed.
Exit code: 127
Command: husky install
Arguments: 
Directory: /Users/iradchenko/sandbox/ember-context-test/node_modules/@alexlafroscia/ember-context
Output:
/bin/sh: husky: command not found
```

**Comment by alexlafroscia** [comment]
Are you installing from GitHub or something rather than `npm`?

If I look at the `package.json` that is actually uploaded to `npm` (through `unpkg`) it seems like `husky` is no longer in the post-install script...

https://unpkg.com/@alexlafroscia/ember-context@1.0.0/package.json

**Comment by alexlafroscia** [comment]
The latest version of Husky has a better/simpler Yarn integration; upgrade to that means that Husky should only run as part of the `prepare` script which should only happen locally.
